# Generated by Django 3.2.12 on 2023-07-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(null=True, verbose_name='Telegram id si')),
                ('fakultet_id', models.IntegerField(default=0, verbose_name='fakultet idsi')),
                ('message_id', models.CharField(max_length=1000, null=True, verbose_name='Contractni habar id si')),
                ('full_name', models.CharField(default='', max_length=200, null=True, verbose_name='Toliq ismi sharifi')),
                ('phone', models.CharField(default='', max_length=100, null=True, unique=True, verbose_name='Telefon raqam')),
                ('extra_phone', models.CharField(default='', max_length=100, null=True, verbose_name='Qoshimcha raqam')),
                ('state', models.CharField(choices=[('new', 'Toldirilmagan shartnoma'), ('registered', "Registraciyadan o'tdi"), ('archive', 'Arhivlandi'), ('accepted', 'Qabul qilindi')], default='registered', max_length=100, null=True, verbose_name='Contract holati')),
                ('result', models.IntegerField(default=0, null=True, verbose_name='Togri topilgan javoblar soni')),
                ('dtm', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='DTM test natijasi')),
                ('address', models.CharField(max_length=1000, null=True, verbose_name='Propiska joyi')),
                ('passport', models.CharField(max_length=100, null=True, unique=True, verbose_name='Passport raqami')),
                ('passport_photo', models.CharField(max_length=1000, null=True, verbose_name='Passoprt rasmini idsi')),
                ('diplom', models.CharField(max_length=1500, null=True, verbose_name='Talabaning Diplom yoki attestati')),
                ('jshshir', models.CharField(max_length=30, null=True, verbose_name='JSHSHIR')),
                ('created', models.DateField(null=True, verbose_name='Shartnoma yaratilgan sana')),
            ],
            options={
                'db_table': 'CONTRACT',
            },
        ),
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Fakultet nomi')),
                ('lang', models.CharField(choices=[('ru', 'Russian'), ('uz', 'O'zbek')], default='uz', max_length=12, verbose_name='Fakultet tili')),
                ('time', models.CharField(choices=[('daytime', 'Kunduzgi'), ('evening', 'Kechki'), ('distance', 'Sirtqi')], max_length=100, verbose_name='Talim shakli')),
                ('summa', models.IntegerField(verbose_name='Contract summasi')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Savol raqami')),
                ('question', models.TextField(max_length=1000, verbose_name='Savol')),
                ('answer', models.CharField(max_length=1, verbose_name='JAVOBI')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='Telegramdagi Ismi')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Telegram username')),
                ('state', models.CharField(default='menu::::', max_length=150, verbose_name='User state')),
                ('telegram_id', models.BigIntegerField(default=1, unique=True, verbose_name='Telegram ID')),
            ],
        ),
    ]
