# Generated by Django 3.2.8 on 2023-07-13 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attemps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='user id')),
                ('state', models.CharField(max_length=100, verbose_name='Holati')),
                ('user_phone', models.CharField(max_length=100, verbose_name='Telefon raqam')),
                ('result', models.IntegerField(verbose_name='Togri topilgan javoblar soni')),
            ],
        ),
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Fakultet nomi')),
                ('time', models.CharField(choices=[('daytime', 'Kunduzgi'), ('evening', 'Kechki'), ('distance', 'Sirtqi')], max_length=100, verbose_name='Talim shakli')),
                ('summa', models.IntegerField(verbose_name='Contract summasi')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=200, verbose_name='Savol')),
                ('variants', models.CharField(max_length=1000, verbose_name='Variantlar')),
                ('answer', models.CharField(max_length=1, verbose_name='Togri javob')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Telegram username')),
                ('telegram_id', models.BigIntegerField(default=1, unique=True, verbose_name='Telegram ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fakultet_id', models.IntegerField(default=0, verbose_name='fakultet idsi')),
                ('full_name', models.CharField(default='', max_length=200, verbose_name='Toliq ismi sharifi')),
                ('phone', models.CharField(default='', max_length=100, verbose_name='Telefon raqam')),
                ('extra_phone', models.CharField(default='', max_length=100, verbose_name='Qoshimcha raqam')),
                ('state', models.CharField(default='', max_length=100, verbose_name='Contract holati')),
                ('time', models.CharField(default='', max_length=50, verbose_name='Talim shakli')),
                ('result', models.IntegerField(default=0, verbose_name='Togri topilgan javoblar soni')),
                ('address', models.CharField(max_length=1000, verbose_name='Propiska joyi')),
                ('passport', models.CharField(max_length=100, verbose_name='Passport raqami')),
                ('attempt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attemps')),
            ],
        ),
    ]
