# Generated by Django 3.2.8 on 2023-07-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Fakultet nomi')),
                ('lang', models.CharField(choices=[('ru', 'Russian'), ('uz', 'Uzbek')], default='uz', max_length=12, verbose_name='Fakultet tili')),
                ('time', models.CharField(choices=[('daytime', 'Kunduzgi'), ('evening', 'Kechki'), ('distance', 'Sirtqi')], max_length=100, verbose_name='Talim shakli')),
                ('summa', models.IntegerField(verbose_name='Contract summasi')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Savol raqami')),
                ('question', models.TextField(max_length=1000, verbose_name='Savol')),
                ('answer', models.CharField(max_length=1, verbose_name='JAVOBI')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='Telegramdagi Ismi')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Telegram username')),
                ('state', models.CharField(default='menu::::', max_length=150, verbose_name='User state')),
                ('telegram_id', models.BigIntegerField(default=1, unique=True, verbose_name='Telegram ID')),
            ],
        ),
    ]
