# Generated by Django 3.2.8 on 2023-07-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(null=True, verbose_name='Telegram id si')),
                ('fakultet_id', models.IntegerField(default=0, verbose_name='fakultet idsi')),
                ('message_id', models.CharField(max_length=1000, null=True, verbose_name='Contractni habar id si')),
                ('full_name', models.CharField(default='', max_length=200, null=True, verbose_name='Toliq ismi sharifi')),
                ('phone', models.CharField(default='', max_length=100, null=True, unique=True, verbose_name='Telefon raqam')),
                ('extra_phone', models.CharField(default='', max_length=100, null=True, verbose_name='Qoshimcha raqam')),
                ('state', models.CharField(choices=[('new', 'Toldirilmagan shartnoma'), ('registered', "Registraciyadan o'tdi"), ('archive', 'Arhivlandi'), ('accepted', 'Qabul qilindi')], default='registered', max_length=100, null=True, verbose_name='Contract holati')),
                ('result', models.IntegerField(default=0, null=True, verbose_name='Togri topilgan javoblar soni')),
                ('dtm', models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='DTM test natijasi')),
                ('address', models.CharField(max_length=1000, null=True, verbose_name='Propiska joyi')),
                ('passport', models.CharField(max_length=100, null=True, unique=True, verbose_name='Passport raqami')),
                ('passport_photo', models.CharField(max_length=1000, null=True, verbose_name='Passoprt rasmini idsi')),
                ('diplom', models.CharField(max_length=1500, null=True, verbose_name='Talabaning Diplom yoki attestati')),
                ('jshshir', models.CharField(max_length=30, null=True, verbose_name='JSHSHIR')),
                ('created', models.DateField(null=True, verbose_name='Shartnoma yaratilgan sana')),
            ],
        ),
    ]
