# Generated by Django 3.2.8 on 2023-07-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakultet',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], default='uz', max_length=2, verbose_name='Fakultet tili'),
        ),
    ]
