# Generated by Django 3.2.12 on 2023-07-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contract',
            table=None,
        ),
    ]
