# Generated by Django 3.2.8 on 2023-07-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='passport',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Passport raqami'),
        ),
    ]
