# Generated by Django 3.2.12 on 2023-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakultet',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Rus tili'), ('uz', 'Uzbek')], default='uz', max_length=12, verbose_name='Fakultet tili'),
        ),
        migrations.AlterField(
            model_name='fakultet',
            name='summa_text',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Contractni summasini text formati'),
        ),
    ]
