# Generated by Django 3.2.8 on 2023-07-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_contract_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='diplom',
            field=models.CharField(max_length=1500, null=True, verbose_name='Talabaning Diplom yoki attestati'),
        ),
        migrations.AddField(
            model_name='contract',
            name='dtm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='DTM test natijasi'),
        ),
    ]
