# Generated by Django 3.2.8 on 2023-07-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_contract'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contract',
            table='CONTRACT',
        ),
    ]
