# Generated by Django 3.2.12 on 2023-07-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230720_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_link',
        ),
        migrations.AlterField(
            model_name='fakultet',
            name='lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('uz', 'Uzbek')], default='uz', max_length=12, verbose_name='Fakultet tili'),
        ),
    ]
