# Generated by Django 3.2.8 on 2023-07-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_fakultet_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='attempt_id',
        ),
        migrations.AddField(
            model_name='contract',
            name='message_id',
            field=models.CharField(max_length=1000, null=True, verbose_name='Contractni habar id si'),
        ),
        migrations.AddField(
            model_name='contract',
            name='passport_photo',
            field=models.CharField(max_length=1000, null=True, verbose_name='Passoprt rasmini idsi'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=1000, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_phone',
            field=models.CharField(max_length=100, null=True, verbose_name='Qoshicha telefon raqam'),
        ),
        migrations.AddField(
            model_name='user',
            name='jshshir',
            field=models.CharField(max_length=30, null=True, verbose_name='JSHSHIR'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(max_length=20, null=True, verbose_name='Passport id si'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='Telefon raqam'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_id',
            field=models.CharField(max_length=1500, null=True, verbose_name='Photo ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='result',
            field=models.IntegerField(default=0, verbose_name='Togri javoblar soni'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='menu::::', max_length=150, verbose_name='User state'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='unregistered', max_length=30, verbose_name='User statusi'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='passport',
            field=models.CharField(max_length=100, unique=True, verbose_name='Passport raqami'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='phone',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='fakultet',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Fakultet nomi'),
        ),
        migrations.DeleteModel(
            name='Attemps',
        ),
    ]
