# Generated by Django 3.2.8 on 2023-07-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_contract_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='message_id',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_link',
            field=models.CharField(default='', max_length=1000, null=True, verbose_name='Contractni habar linki'),
        ),
        migrations.AddField(
            model_name='fakultet',
            name='summa_text',
            field=models.CharField(default='', max_length=100, verbose_name='Contractni summasini text formati'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='dtm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='DTM test natijasi'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='result',
            field=models.IntegerField(default=0, verbose_name='Togri topilgan javoblar soni'),
        ),
    ]
