# Generated by Django 3.2.8 on 2023-07-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230714_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakultet',
            name='lang',
            field=models.CharField(default='uz', max_length=12, verbose_name='Fakultet tili'),
        ),
        migrations.AlterField(
            model_name='fakultet',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Fakultet nomi'),
        ),
        migrations.AlterField(
            model_name='fakultet',
            name='time',
            field=models.CharField(max_length=100, verbose_name='Talim shakli'),
        ),
    ]
