# Generated by Django 3.2.12 on 2023-07-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_contract_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='dtm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='DTM test natijasi'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='message_id',
            field=models.CharField(default='', max_length=1000, verbose_name='Contractni habar id si'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='result',
            field=models.IntegerField(default=0, verbose_name='Togri topilgan javoblar soni'),
        ),
    ]
