# Generated by Django 3.2.12 on 2023-07-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230720_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakultet',
            name='lang',
            field=models.CharField(choices=[('ru', 'Rus tili'), ('uz', "O'zbek")], default='uz', max_length=12, verbose_name='Fakultet tili'),
        ),
    ]
