# Generated by Django 3.2.8 on 2023-07-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230718_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created',
            field=models.TimeField(null=True, verbose_name='Shartnoma yaratilgan sana'),
        ),
    ]
