# Generated by Django 3.2.12 on 2023-07-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_fakultet_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakultet',
            name='lang',
            field=models.CharField(choices=[('en', 'Ingliz'), ('ru', 'Rus tili'), ('uz', "O'zbek")], default='uz', max_length=12, verbose_name='Fakultet tili'),
        ),
    ]
