# Generated by Django 3.2.12 on 2023-07-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230718_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='message_id',
            field=models.CharField(default='', max_length=1000, null=True, verbose_name='Contractni habar id si'),
        ),
    ]
