# Generated by Django 3.2.8 on 2023-07-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230715_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakultet',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], default='uz', max_length=12, verbose_name='Fakultet tili'),
        ),
        migrations.AlterField(
            model_name='fakultet',
            name='time',
            field=models.CharField(choices=[('daytime', 'Kunduzgi'), ('evening', 'Kechki'), ('distance', 'Sirtqi')], max_length=100, verbose_name='Talim shakli'),
        ),
    ]
