# Generated by Django 3.2.12 on 2023-07-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_contract_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='message_id',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_link',
            field=models.CharField(default='', max_length=1000, null=True, verbose_name='Contractni habar linki'),
        ),
    ]
