# Generated by Django 3.2.8 on 2023-07-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230715_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='', max_length=150, verbose_name='Toliq ism sharifi'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(default='waiting', max_length=100, verbose_name='Contract holati'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Telegramdagi Ismi'),
        ),
    ]
