# Generated by Django 3.2.8 on 2023-09-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_fakultet_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='education',
            field=models.CharField(max_length=50, null=True, verbose_name='Oqish shakli va talim tili'),
        ),
    ]
