# Generated by Django 3.2.8 on 2023-07-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20230715_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_id',
            field=models.CharField(max_length=1500, null=True, verbose_name='Passport Photo ID'),
        ),
    ]
