# Generated by Django 3.2.12 on 2023-07-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230719_1611'),
        ('products', '0006_auto_20230719_1510'),
    ]

    operations = [
    ]
