# Generated by Django 3.2.8 on 2023-07-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230715_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Toliq ism sharifi'),
        ),
    ]
