# Generated by Django 3.2.8 on 2023-07-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_user_real_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Savol raqami')),
                ('question', models.TextField(max_length=1000, verbose_name='Savol')),
                ('answer', models.CharField(max_length=1, verbose_name='JAVOBI')),
            ],
        ),
        migrations.AlterField(
            model_name='fakultet',
            name='lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('uz', 'Uzbek')], default='uz', max_length=12, verbose_name='Fakultet tili'),
        ),
    ]
