# Generated by Django 3.2.8 on 2023-07-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230716_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='telegram_id',
            field=models.IntegerField(null=True, verbose_name='Telegram id si'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('registered', "Registraciyadan o'tdi"), ('arhive', 'Arhivlandi'), ('accepted', 'Qabul qilindi')], default='registered', max_length=100, verbose_name='Contract holati'),
        ),
    ]
