# Generated by Django 3.2.8 on 2023-07-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20230716_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='jshshir',
            field=models.CharField(max_length=30, null=True, verbose_name='JSHSHIR'),
        ),
    ]
