# Generated by Django 3.2.8 on 2023-07-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_contract_jshshir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='time',
        ),
    ]
