# Generated by Django 3.2.8 on 2023-07-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_contract_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='telegram_id',
            field=models.BigIntegerField(null=True, verbose_name='Telegram id si'),
        ),
    ]
