# Generated by Django 3.2.12 on 2023-07-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_contract_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('registered', "Registraciyadan o'tdi"), ('archive', 'Arhivlandi'), ('accepted', 'Qabul qilindi')], default='registered', max_length=100, verbose_name='Contract holati'),
        ),
    ]
